spring:
  application:
    name: jupiter
  data:
    mongodb:
      uri: mongodb+srv://harshrghvnsh:sBxdyMeJsfOHV2T7@cluster1.mb4ef.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
      database: Jupiter
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8080